# Generated by Django 5.2.6 on 2026-08-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_admintransferbeneficiary_admintransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admintransfer',
            options={'ordering': ['-created_at'], 'permissions': [('initiate_admin_transfer', 'Can initiate administrative bank transfers')]},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at'], 'permissions': [('approve_withdrawal', 'Can accept or reject user withdrawal requests')]},
        ),
    ]
