# Generated by Django 5.2.12 on 2026-04-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_index_sql(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP INDEX IF EXISTS "users_user_referral_code_b937ce54_like";')

def drop_column_sql(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE "users_user" DROP COLUMN IF EXISTS "referral_code";')

def create_index_sql(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('CREATE INDEX IF NOT EXISTS "users_user_referral_code_b937ce54_like" ON "users_user" ("referral_code" varchar_pattern_ops);')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_bvn_remove_user_tier'),
    ]

    operations = [
        migrations.RunPython(drop_index_sql, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(drop_column_sql, reverse_code=migrations.RunPython.noop),

        migrations.CreateModel(
            name='ReferralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable the referral program.')),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage of Sale'), ('flat', 'Flat Amount')], default='flat', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=100.0, help_text='If percentage: e.g. 5.00 means 5%. If flat: e.g. 100.00 means ₦100.', max_digits=10)),
                ('commission_mode', models.CharField(choices=[('signup', 'One-time on Signup'), ('recurring', 'Recurring on Every Purchase')], default='signup', help_text="'signup' = bonus when referred user signs up. 'recurring' = bonus on each purchase.", max_length=20)),
                ('min_purchase_for_recurring', models.DecimalField(decimal_places=2, default=0, help_text='Minimum purchase amount to trigger recurring referral bonus.', max_digits=10)),
                ('max_referral_bonus_per_user', models.DecimalField(decimal_places=2, default=0, help_text='Max total bonus a referrer can earn from one referred user. 0 = unlimited.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Referral Configuration',
                'verbose_name_plural': 'Referral Configuration',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='agent_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default commission rate (%) for agent transactions.', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=False, max_length=20, null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                User := apps.get_model('users', 'User'),
                [setattr(u, 'referral_code', f"REF{u.id}{apps.get_model('users', 'User').objects.count() + 1000}") or u.save() for u in User.objects.all()]
            ),
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=False, max_length=20, unique=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent/Reseller'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_pin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='upgraded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upgraded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_paid', models.BooleanField(default=False)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_rel', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('tv', 'TV'), ('education', 'Education'), ('smile', 'Smile'), ('transfer', 'Wallet Transfer'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('identifier', models.CharField(help_text='Phone, meter number, smartcard, account number, etc.', max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra info, e.g. {"network":"mtn", "bank_code":"044", "bank_name":"Access Bank"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'service_type', 'identifier')},
            },
        ),
        migrations.RunPython(create_index_sql, reverse_code=migrations.RunPython.noop),
    ]

