# Generated by Django 5.2.6 on 2026-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0016_remove_siteconfig_agent_pricing_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='developer_upgrade_kyc_required',
            field=models.BooleanField(default=False, help_text='If enabled, user must be KYC verified to upgrade to developer.'),
        ),
    ]
