# Generated by Django 5.2.6 on 2026-08-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0017_user_is_admin_field_role_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False, help_text='Automatically sync plans/networks from all active providers.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='auto_sync_frequency',
            field=models.PositiveIntegerField(default=24, help_text='Sync every N hours.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='auto_sync_last_run',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='auto_sync_next_run',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='auto_sync_time',
            field=models.TimeField(default='02:00', help_text='Preferred daily start time (server local time).'),
        ),
    ]
