# Generated by Django 5.2.6 on 2026-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_wallettransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='receiver_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='receiver_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='receiver_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='sender_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='sender_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='sender_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
