# Generated by Django 5.2.6 on 2026-08-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_wallettransaction_receiver_account_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'permissions': [('adjust_wallet', 'Can adjust user wallet balance manually')]},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-timestamp'], 'permissions': [('adjust_wallet', 'Can adjust user wallet balance manually')]},
        ),
    ]
