# Generated by Django 5.2.6 on 2026-08-15 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_wallet_options_alter_wallettransaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for the charge rule, e.g. Deposit processing fee', max_length=255)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_others', 'Transfer (Others)'), ('transfer_p2p', 'Transfer (P2P)')], db_index=True, max_length=30)),
                ('charge_type', models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='flat', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Flat fee amount or percentage rate (0-100)', max_digits=12)),
                ('cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fee cap when percentage type is used (null means no cap)', max_digits=12, null=True)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum transaction amount to apply this charge', max_digits=12)),
                ('max_transaction_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum transaction amount to apply this charge (null means no upper limit)', max_digits=12, null=True)),
                ('block_if_insufficient', models.BooleanField(default=False, help_text='Prevent transaction if wallet balance is insufficient for amount + charge. If False, charge is skipped if balance is insufficient.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Charge',
                'verbose_name_plural': 'Transaction Charges',
                'ordering': ['transaction_type', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='charge_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_transactions', to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='is_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
