# Generated by Django 5.2.6 on 2026-08-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_transactioncharge_wallettransaction_charge_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncharge',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('transfer_others', 'Transfer (Others)'), ('transfer_p2p', 'Transfer (P2P)')], db_index=True, max_length=30),
        ),
    ]
