# Generated by Django 5.2.6 on 2026-08-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalpermission',
            name='action',
            field=models.CharField(choices=[('view', 'View (Read)'), ('add', 'Add (Create)'), ('change', 'Change (Update)'), ('delete', 'Delete'), ('adjust_wallet', 'Manual Wallet Adjustment'), ('initiate_admin_transfer', 'Initiate Admin Transfer'), ('manual_purchase', 'Manual Purchase Execution'), ('approve_withdrawal', 'Approve/Reject Withdrawal'), ('send_notification', 'Send Notifications'), ('send_announcement', 'Send Announcements')], max_length=50),
        ),
    ]
