# Generated by Django 5.2.6 on 2026-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_vtuproviderconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='vtuproviderconfig',
            name='name',
            field=models.CharField(choices=[('vtpass', 'VTPass'), ('clubkonnect', 'ClubKonnect'), ('arewa_global', 'Arewa Global'), ('alrahuz', 'Alrahuz Data'), ('smedata', 'SMEDATA.NG'), ('mobilenig', 'MobileNig'), ('mobilevtu', 'MobileVTU'), ('nata', 'Nata API'), ('amigo', 'Amigo'), ('vtuorg', 'vtu.org'), ('flowpay', 'FlowPay'), ('ketamency', 'Ketamency (Smile)')], max_length=20, unique=True),
        ),
    ]
