# Generated by Django 5.2.12 on 2026-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_purchase_metadata_alter_vtuproviderconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimenetwork',
            name='developer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='datavariation',
            name='developer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='educationvariation',
            name='developer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='electricityvariation',
            name='developer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='internetvariation',
            name='developer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerouting',
            name='developer_margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount/percentage to add to cost for developers', max_digits=10),
        ),
        migrations.AddField(
            model_name='tvvariation',
            name='developer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
