# Generated by Django 5.2.12 on 2026-07-13 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_airtimenetwork_developer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationvariation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationvariation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
