# Generated by Django 5.2.12 on 2026-07-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_educationvariation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtimenetwork',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dataservice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='educationservice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='electricityservice',
            options={'ordering': ['id'], 'verbose_name': 'Electricity Service', 'verbose_name_plural': 'Electricity Services'},
        ),
        migrations.AlterModelOptions(
            name='internetservice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tvservice',
            options={'ordering': ['id'], 'verbose_name': 'TV Service', 'verbose_name_plural': 'TV Services'},
        ),
    ]
