# Generated by Django 5.2.6 on 2026-08-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_alter_airtimenetwork_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('tv', 'Cable TV'), ('electricity', 'Electricity'), ('internet', 'Internet'), ('education', 'Education')], max_length=20)),
                ('catalogue_source', models.CharField(choices=[('db', 'Local Database'), ('live', 'Live from Provider API')], default='db', help_text='Where to source plans/networks on API requests for this service.', max_length=10)),
                ('live_cache_ttl_seconds', models.PositiveIntegerField(default=300, help_text='How long (seconds) to cache live-fetched data. 0 = no cache.')),
                ('customer_margin_type', models.CharField(choices=[('flat', 'Flat Amount (₦)'), ('percentage', 'Percentage (%)')], default='flat', max_length=15)),
                ('customer_margin_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Add this flat amount or percentage on top of cost for regular users.', max_digits=12)),
                ('agent_margin_type', models.CharField(choices=[('flat', 'Flat Amount (₦)'), ('percentage', 'Percentage (%)')], default='flat', max_length=15)),
                ('agent_margin_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Add this flat amount or percentage on top of cost for agents/affiliates.', max_digits=12)),
                ('developer_margin_type', models.CharField(choices=[('flat', 'Flat Amount (₦)'), ('percentage', 'Percentage (%)')], default='flat', max_length=15)),
                ('developer_margin_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Add this flat amount or percentage on top of cost for API developers.', max_digits=12)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_configs', to='orders.vtuproviderconfig')),
            ],
            options={
                'verbose_name': 'Provider Service Config',
                'verbose_name_plural': 'Provider Service Configs',
                'unique_together': {('provider', 'service_type')},
            },
        ),
    ]
