# Generated by Django 5.2.6 on 2026-08-05 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_providerserviceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this scheduled sync job', max_length=255)),
                ('service_type', models.CharField(choices=[('all', 'All Services'), ('airtime', 'Airtime'), ('data', 'Data'), ('tv', 'Cable TV'), ('electricity', 'Electricity'), ('internet', 'Internet'), ('education', 'Education')], default='all', max_length=20)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the schedule should start running')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this job schedule')),
                ('last_run', models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_run', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Select a specific provider or leave empty for All Active Providers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_schedules', to='orders.vtuproviderconfig')),
            ],
            options={
                'verbose_name': 'Auto Sync Schedule',
                'verbose_name_plural': 'Auto Sync Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=255)),
                ('provider_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], max_length=20)),
                ('items_synced', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='orders.autosyncschedule')),
            ],
            options={
                'verbose_name': 'Auto Sync Log',
                'verbose_name_plural': 'Auto Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
