# Generated by Django 5.2.6 on 2026-08-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_autosyncschedule_autosynclog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-time'], 'permissions': [('manual_purchase', 'Can execute manual VTU purchases')]},
        ),
    ]
