# Generated by Django 5.2.6 on 2026-08-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_announcement_created_by_notification_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'permissions': [('send_announcement', 'Can create and broadcast announcements')]},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'permissions': [('send_notification', 'Can send notifications and announcements to users')]},
        ),
    ]
